### ISSUE TITLE
So oil burns so its pruducts should too

### ISSUE THREAD

**Issue by CA6** [What42Pizza/Mindustry-Production-Mod#1]
Um so light, heavy oil and potrulium should A)burn
B) not be really hot

Side note a napalm canon or naplam bomber would make sense. with the existing items and fluids naplam would not be hard to add. 

Love the mod keep up the good work.

**Comment by What42Pizza** [comment]
Light oil, heavy oil, and petroleum all do burn blocks that are placed on them after they have been spilled, so I'm not sure what you mean when you say they should burn. I've just realized you can't put them in wave turrets though, so I definitely should add that.
Also, I don't know what you mean when you say they shouldn't be really hot. Your suggestions about napalm are pretty good I'm definitely going to add those to the TODO list.

**Comment by CA6** [comment]
Ok so when introduced to high temp the oils would lite aflame (falmabitity) not catch things on fire ie currently when they're introduced to slag nothing happens but when tar contacts it the tar goes up it's a flavor thing tbh but \_(▪_▪)_/. I appreciate the adding naplam
