### ISSUE TITLE
Мод?

### ISSUE THREAD

**Issue by TheseusAgeyson** [What42Pizza/Mindustry-Production-Mod#11]
Когда можно будет скачать мод?

**Comment by What42Pizza** [comment]
Я использую для этого Google Translate, поэтому не знаю, насколько хорошо это будет работать, но вот что вам нужно сделать:
1: Откройте игру и перейдите в меню модов
2: Нажмите кнопку «импортировать мод github».
3: введите what42pizza/mindustry-production-mod и нажмите ОК
Надеюсь, это сработает! Сообщите, если у вас возникнут проблемы.
