### ISSUE TITLE
Steel forge does not build, even with all required resources

### ISSUE THREAD

**Issue by connormcdermid** [What42Pizza/Mindustry-Production-Mod#2]
Platform: PC.
Other mods: Teleporter Mod.
Running on a server.

The steel forge is selectable in menus, is not greyed out, and shows that it has enough resources to be built. However, when placed, it continually resets build progress to 0, making sure the building is never completed.

**Comment by Cyannetzine** [comment]
Ff

**Comment by MasterNo2** [comment]
that is typically because ur on a server

**Comment by connormcdermid** [comment]
Yes, I am on a server. Does this mod not support servers?

**Comment by MasterNo2** [comment]
It works, it is just that Mindustry multiplayer games/servers often don't interact well with mods. It is typically whoever is the host shows whatever is correct. When running multiple mods, occasionally just one, it can show that you built some thing else as well. Your players can fix this by relogging (leaving the server to rejoin). Hope this helps! (I have run into problems with things like this too.)
