### ISSUE TITLE
Petroleum containers/ filler

### ISSUE THREAD

**Issue by HappyGingerWolf** [What42Pizza/Mindustry-Production-Mod#3]
Platform: Android
Other mods: None

The petroleum filler requires 2.5 petroleum to fill a container, but when emptied each container has 5 petroleum. This means that a tiny setup with a filler and emptier feeding each other can produce 2.5 petroleum a second for only 10 power units, which is obviously very OP.

I love the mod otherwise though, very creative and fun.

**Comment by HappyGingerWolf** [comment]
Oh also, you said to contact you over discord, but to do that you need to give the four digits after your name also.

**Comment by What42Pizza** [comment]
Sorry about responding so late, but I've fixed the problem now. Actually, I fixed it a while ago. Also, I'm new to discord and didn't realize I needed to have those numbers, so thank you for telling me.
