### ISSUE TITLE
Base Infiltration?

### ISSUE THREAD

**Issue by DatOnePlayer** [What42Pizza/Mindustry-Production-Mod#4]
Do you have any intentions on fixing this map? It looks cool, not to rush just asking

**Comment by What42Pizza** [comment]
Sorry for responding so late, but I don't have any plans to fix the map. If I were to fix it, I would first have to find a version of the mod where it does work, use that version to remove every last bit that is modded, then move to the new version and add back everything I removed. And every time I add new material, there is a chance the map will break again.
